Blogsite/Controllers/admin_weblinksController.cs
using System;
using System.Web.Mvc;

namespace Annytab.Blogsite.Controllers
{
    /// <summary>
    /// This class controls the administration of weblinks
    /// </summary>
    [ValidateInput(false)]
    public class admin_weblinksController : Controller
    {
        #region View methods

        // Get the list of weblinks
        // GET: /admin_weblinks/
        [HttpGet]
        public ActionResult index()
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query paramaters
            ViewBag.QueryParams = new QueryParams(Request);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View();
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

        } // End of the index method

        // Search in the list
        // POST: /admin_weblinks/search
        [HttpPost]
        public ActionResult search(FormCollection collection)
        {
            // Get the search data
            string keywordString = collection["txtSearch"];
            string sort_field = collection["selectSortField"];
            string sort_order = collection["selectSortOrder"];
            string page_size = collection["selectPageSize"];

            // Return the url with search parameters
            return Redirect("/admin_weblinks?kw=" + Server.UrlEncode(keywordString) + "&sf=" + sort_field + "&so=" + sort_order + "&pz=" + page_size);

        } // End of the search method

        // Get the edit form
        // GET: /admin_weblinks/edit
        [HttpGet]
        public ActionResult edit(Int32 id = 0, string returnUrl = "/admin_weblinks")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default admin language
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Add data to the view
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.Weblink = Weblink.GetOneById(id, adminLanguageId);
            ViewBag.ReturnUrl = returnUrl;

            // Create new empty weblink if the weblink does not exist
            if (ViewBag.Weblink == null)
            {
                // Add data to the view
                ViewBag.Weblink = new Weblink();
            }

            // Return the edit view
            return View("edit");

        } // End of the edit method

        // Get the translate form
        // GET: /admin_weblinks/translate
        [HttpGet]
        public ActionResult translate(Int32 id = 0, string returnUrl = "/admin_weblinks")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor", "Translator" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default admin language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get the language id
            int languageId = 0;
            if (Request.Params["lang"] != null)
            {
                Int32.TryParse(Request.Params["lang"], out languageId);
            }

            // Add data to the form
            ViewBag.LanguageId = languageId;
            ViewBag.Languages = Language.GetAll(adminLanguageId, "name", "ASC");
            ViewBag.StandardWeblink = Weblink.GetOneById(id, adminLanguageId);
            ViewBag.TranslatedWeblink = Weblink.GetOneById(id, languageId);
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.ReturnUrl = returnUrl;

            // Return the view
            if (ViewBag.StandardWeblink != null)
            {
                return View("translate");
            }
            else
            {
                return Redirect(returnUrl);
            }

        } // End of the translate method

        #endregion

        #region Post methods

        // Update the weblink
        // POST: /admin_weblinks/edit
        [HttpPost]
        public ActionResult edit(FormCollection collection)
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            string returnUrl = collection["returnUrl"];
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get all the form values
            Int32 id = Convert.ToInt32(collection["txtId"]);
            string link_name = collection["txtLinkname"];
            string url = collection["txtUrl"];
            string rel = collection["selectRelation"];
            string target = collection["selectTarget"];
            bool inactive = Convert.ToBoolean(collection["cbInactive"]);

            // Get the default admin language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get translated texts
            KeyStringList tt = StaticText.GetAll(adminLanguageId, "id", "ASC");

            // Get the weblink
            Weblink weblink = Weblink.GetOneById(id, adminLanguageId);

            // Check if the weblink exists
            if (weblink == null)
            {
                // Create an empty weblink
                weblink = new Weblink();
            }

            // Update values
            weblink.rel = rel;
            weblink.target = target;
            weblink.link_name = link_name;
            weblink.url = url;
            weblink.inactive = inactive;

            // Create a error message
            string errorMessage = string.Empty;

            // Check for errors
            if (weblink.link_name.Length > 100)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_length"), tt.Get("linkname"), "100") + "<br/>";
            }
            if (weblink.url.Length > 100)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_length"), tt.Get("url"), "100") + "<br/>";
            }
            
            // Check if there is errors
            if (errorMessage == string.Empty)
            {
                // Check if we should add or update the weblink
                if (weblink.id == 0)
                {
                    // Add the weblink
                    Int64 insertId = Weblink.AddMasterPost(weblink);
                    weblink.id = Convert.ToInt32(insertId);
                    Weblink.AddLanguagePost(weblink, adminLanguageId);
                }
                else
                {
                    // Update the weblink
                    Weblink.UpdateMasterPost(weblink);
                    Weblink.UpdateLanguagePost(weblink, adminLanguageId);
                }

                // Redirect the user to the list
                return Redirect(returnUrl);
            }
            else
            {
                // Set form values
                ViewBag.ErrorMessage = errorMessage;
                ViewBag.Weblink = weblink;
                ViewBag.TranslatedTexts = tt;

Blogsite/Views/admin_weblinks/_form_menu.cshtml
@{
    // Get the form data
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_weblinks" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;
    
    // Get translated texts
    string show_tt = tt.Get("show");
    string list_tt = tt.Get("list");
    string new_tt = tt.Get("new");
    string search_tt = tt.Get("search");
    string id_tt = tt.Get("id");
    string linkname_tt = tt.Get("linkname");
    string url_tt = tt.Get("url");
    string inactive_tt = tt.Get("inactive");
    string ascending_tt = tt.Get("ascending");
    string descending_tt = tt.Get("descending");
    string sort_tt = tt.Get("sort");
    string on_tt = tt.Get("on");
}

@*The menu bar*@
<div class="annytab-form-menubar">
    @using (Html.BeginForm("search", "admin_weblinks", FormMethod.Post))
    {
        <input type="button" class="annytab-form-button" value="@(show_tt + " " + list_tt.ToLower())" onclick="location.href='@Url.Action("index", "admin_weblinks", new { sf = parameters.sort_field, so = parameters.sort_order, pz = parameters.page_size })'" />
        <input type="button" class="annytab-form-button" value="@new_tt" onclick="location.href='@Url.Action("edit", "admin_weblinks", new { id = 0, returnUrl = queryString })'" />
        <select name="selectSortField" class="annytab-form-select" style="width:100px;">
            <option value="id" @(parameters.sort_field == "" ? Html.Raw("selected='selected'") : Html.Raw(""))>@(sort_tt + " " + on_tt.ToLower())</option>
            <option value="id" @(parameters.sort_field == "id" ? Html.Raw("selected='selected'") : Html.Raw(""))>@id_tt</option>
            <option value="link_name" @(parameters.sort_field == "link_name" ? Html.Raw("selected='selected'") : Html.Raw(""))>@linkname_tt</option>
            <option value="url" @(parameters.sort_field == "url" ? Html.Raw("selected='selected'") : Html.Raw(""))>@url_tt</option>
            <option value="inactive" @(parameters.sort_field == "inactive" ? Html.Raw("selected='selected'") : Html.Raw(""))>@inactive_tt</option>
        </select>
        <select name="selectSortOrder" class="annytab-form-select" style="width:80px;">
            <option value="ASC" @(parameters.sort_order == "ASC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@ascending_tt</option>
            <option value="DESC" @(parameters.sort_order == "DESC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@descending_tt</option>
        </select>
        <select name="selectPageSize" class="annytab-form-select" style="width:50px;">
            <option value="10" @(parameters.page_size == 10 ? Html.Raw("selected='selected'") : Html.Raw(""))>10</option>
            <option value="20" @(parameters.page_size == 20 ? Html.Raw("selected='selected'") : Html.Raw(""))>20</option>
            <option value="40" @(parameters.page_size == 40 ? Html.Raw("selected='selected'") : Html.Raw(""))>40</option>
            <option value="80" @(parameters.page_size == 80 ? Html.Raw("selected='selected'") : Html.Raw(""))>80</option>
        </select>
        <input id="txtSearch" name="txtSearch" type="text" class="annytab-form-textbox" style="width:150px;" value="@Server.UrlDecode(parameters.keywords)" />
        <input type="submit" class="annytab-form-button" value="@search_tt" />
    }
</div>

Blogsite/Views/admin_weblinks/edit.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get form data
    Weblink weblink = ViewBag.Weblink;
    KeyStringList tt = ViewBag.TranslatedTexts;
    string returnUrl = ViewBag.ReturnUrl;
    string error_message = ViewBag.ErrorMessage != null ? ViewBag.ErrorMessage : string.Empty;

    // Get translated texts
    string weblink_tt = tt.Get("weblink");
    string new_tt = tt.Get("new");
    string edit_tt = tt.Get("edit");
    string id_tt = tt.Get("id");
    string linkname_tt = tt.Get("linkname");
    string url_tt = tt.Get("url");
    string relation_tt = tt.Get("relation");
    string target_tt = tt.Get("target");
    string inactive_tt = tt.Get("inactive");
    string save_tt = tt.Get("save");
    string cancel_tt = tt.Get("cancel");

    // Set the title for the page
    if (weblink.id == 0)
    {
        ViewBag.Title = weblink_tt + " - " + new_tt.ToLower();
    }
    else
    {
        ViewBag.Title = weblink_tt + " - " + edit_tt.ToLower();
    }
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_weblinks/_form_menu.cshtml")

@*Main form*@
@using (Html.BeginForm("edit", "admin_weblinks", FormMethod.Post))
{
    @*Hidden data*@
    <input name="returnUrl" type="hidden" value="@returnUrl" />
    <div class="annytab-form-error-message" style="@(error_message != "" ? "display:block;" : "display:none;")">@Html.Raw(error_message)</div>
    
    @*Input form table*@
    <div class="annytab-input-form-table">
        <div class="annytab-input-form-row" style="@(weblink.id != 0 ? "display:table-row;" : "display:none;")">
            <div class="annytab-input-form-column-label">@(id_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtId" type="text" class="annytab-form-textbox" tabindex="-1" readonly="readonly" value="@weblink.id" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(linkname_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input id="txtLinkname" name="txtLinkname" type="text" class="annytab-form-textbox" value="@weblink.link_name" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(url_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtUrl" type="text" class="annytab-form-textbox" value="@weblink.url" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(relation_tt + ":")</div>
            <div class="annytab-input-form-column-input">
                <select name="selectRelation" class="annytab-form-select">
                    <option value="follow" @(weblink.rel == "follow" ? Html.Raw("selected='selected'") : Html.Raw(""))>follow</option>
                    <option value="nofollow" @(weblink.rel == "nofollow" ? Html.Raw("selected='selected'") : Html.Raw(""))>nofollow</option>
                    <option value="author" @(weblink.rel == "author" ? Html.Raw("selected='selected'") : Html.Raw(""))>author</option>
                    <option value="publisher" @(weblink.rel == "publisher" ? Html.Raw("selected='selected'") : Html.Raw(""))>publisher</option>
                    <option value="help" @(weblink.rel == "help" ? Html.Raw("selected='selected'") : Html.Raw(""))>help</option>
                    <option value="license" @(weblink.rel == "license" ? Html.Raw("selected='selected'") : Html.Raw(""))>license</option>
                    <option value="noreferrer" @(weblink.rel == "noreferrer" ? Html.Raw("selected='selected'") : Html.Raw(""))>noreferrer</option>
                    <option value="prefetch" @(weblink.rel == "prefetch" ? Html.Raw("selected='selected'") : Html.Raw(""))>prefetch</option>
                    <option value="search" @(weblink.rel == "search" ? Html.Raw("selected='selected'") : Html.Raw(""))>search</option>
                </select>
            </div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(target_tt + ":")</div>
            <div class="annytab-input-form-column-input">
                <select name="selectTarget" class="annytab-form-select">
                    <option value="_blank" @(weblink.target == "_blank" ? Html.Raw("selected='selected'") : Html.Raw(""))>_blank</option>
                    <option value="_top" @(weblink.target == "_top" ? Html.Raw("selected='selected'") : Html.Raw(""))>_top</option>
                    <option value="_self" @(weblink.target == "_self" ? Html.Raw("selected='selected'") : Html.Raw(""))>_self</option>
                </select>
            </div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(inactive_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="cbInactive" type="checkbox" class="annytab-form-checkbox" value="true" @(weblink != null && weblink.inactive == true ? Html.Raw("checked='checked'") : Html.Raw("")) /></div>
        </div>
    </div>

    @*Button panel*@
    <div style="display:block;border:1px solid #cccccc;margin:20px 0px 0px 0px;border-radius:4px;">
        <input id="btnSave" type="submit" class="annytab-form-button" value="@save_tt" />
        <input type="button" class="annytab-form-button" value="@cancel_tt" onclick="@Html.Raw("location.href='" + returnUrl + "'")" />
    </div>
}

@section scripts {
    <script type="text/javascript">$("#txtLinkname").focus();</script>
}

Blogsite/Views/admin_weblinks/index.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get form data
    Domain domain = ViewBag.CurrentDomain;
    Language currentLanguage = Language.GetOneById(domain.back_end_language);
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_weblinks" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;

    // Create a clean string with keywords
    string cleanKeywords = parameters.keywords.Replace("+", "");

    // Create an array with search words
    string[] words = cleanKeywords.Split(' ');

    // Count the number of posts
    Int32 count = Weblink.GetCountBySearch(words, domain.back_end_language);

    // Get the number of pages
    Int32 numberOfPages = Convert.ToInt32(Math.Ceiling(((double)count / parameters.page_size)));
    numberOfPages = numberOfPages == 0 ? 1 : numberOfPages;

    // Get static pages by keywords in a search
    List<Weblink> weblinks = Weblink.GetBySearch(words, domain.back_end_language, parameters.page_size, parameters.current_page,
        parameters.sort_field, parameters.sort_order);

    // Get translated texts
    string weblink_tt = tt.Get("weblink");
    string list_tt = tt.Get("list");
    string id_tt = tt.Get("id");
    string linkname_tt = tt.Get("linkname");
    string url_tt = tt.Get("url");
    string edit_tt = tt.Get("edit");
    string translate_tt = tt.Get("translate");
    string delete_tt = tt.Get("delete");

    // Set paging data
    ViewBag.CurrentPage = parameters.current_page;
    ViewBag.NumberOfPages = numberOfPages;
    ViewBag.NavigateUrl = "/admin_weblinks?kw=" + Server.UrlEncode(parameters.keywords) + "&sf=" + parameters.sort_field + "&so=" + parameters.sort_order + "&pz=" + parameters.page_size + "&qp={0}";

    // Set the title for the page
    ViewBag.Title = weblink_tt + " - " + list_tt.ToLower();
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_weblinks/_form_menu.cshtml")

@*List of weblinks*@
<div class="annytab-list-container">
    <div class="annytab-list-table" style="width:848px;">
        <div class="annytab-list-row">
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@id_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@linkname_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@url_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@edit_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@translate_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@delete_tt</div>
        </div>

        @for (int i = 0; i < weblinks.Count; i++)
        {
            @:<div class="@(i % 2 != 0 ? "annytab-list-row-main" : "annytab-list-row-alt")">
            @:<div class="annytab-list-column" style="text-align:center;width:100px;">@weblinks[i].id.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@weblinks[i].link_name.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@weblinks[i].url.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@edit_tt" onclick="location.href='@Url.Action("edit", "admin_weblinks", new { id = weblinks[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@translate_tt" onclick="location.href='@Url.Action("translate", "admin_weblinks", new { id = weblinks[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input data-id="deletePost" type="button" class="annytab-form-button" value="@delete_tt" @(Html.Raw("data-url='/admin_weblinks/delete/" + weblinks[i].id + "?returnUrl=" + Server.UrlEncode(queryString) + "'")) /></div>
            @:</div>
        }
    </div>
</div>

@*Paging menu*@
@Html.Partial("/Views/shared_admin/_paging_menu.cshtml")

@section scripts {
    <script type="text/javascript">$("#txtSearch").focus();</script>
}

Blogsite/Views/admin_weblinks/translate.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get values
    Int32 languageId = ViewBag.LanguageId;
    List<Language> languages = ViewBag.Languages;
    Weblink standardWeblink = ViewBag.StandardWeblink;
    Weblink translatedWeblink = ViewBag.TranslatedWeblink;
    KeyStringList tt = ViewBag.TranslatedTexts;
    string returnUrl = ViewBag.ReturnUrl;
    string error_message = ViewBag.ErrorMessage != null ? ViewBag.ErrorMessage : string.Empty;

    // Get translated texts
    string translate_tt = tt.Get("translate");
    string no_choice_tt = tt.Get("no_choice");
    string language_tt = tt.Get("language");
    string weblink_tt = tt.Get("weblink");
    string linkname_tt = tt.Get("linkname");
    string url_tt = tt.Get("url");
    string inactive_tt = tt.Get("inactive");
    string delete_tt = tt.Get("delete");
    string cancel_tt = tt.Get("cancel");

    // Set the title for the page
    ViewBag.Title = weblink_tt + " - " + translate_tt.ToLower();
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_weblinks/_form_menu.cshtml")

@*Main form*@
@using (Html.BeginForm("translate", "admin_weblinks", FormMethod.Post))
{
    @*Hidden data*@
    <input name="returnUrl" type="hidden" value="@returnUrl" />
    <div class="annytab-form-error-message" style="@(error_message != "" ? "display:block;" : "display:none;")">@Html.Raw(error_message)</div>
    <input type="hidden" name="hiddenWeblinkId" value="@standardWeblink.id" />
    
    @*Input form table*@
    <div class="annytab-input-form-table">
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(language_tt + ":")</div>
            <div class="annytab-input-form-column-input">
                <select id="selectLanguage" name="selectLanguage" class="annytab-form-select">
                    <option value="0" data-url="@Url.Content("/admin_weblinks/translate/" + standardWeblink.id.ToString() + "?returnUrl=" + Server.UrlEncode(returnUrl))" @(languageId == 0 ? Html.Raw("selected='selected'") : Html.Raw(""))>@("-- " + no_choice_tt + " --")</option>
                    @foreach (Language language in languages)
                    {
                        <option value="@language.id" data-url="@Url.Content("/admin_weblinks/translate/" + standardWeblink.id.ToString() + "?returnUrl=" + Server.UrlEncode(returnUrl) + "&lang=" + language.id.ToString())" @(language.id == languageId ? Html.Raw("selected='selected'") : Html.Raw(""))>@language.name</option>
                    }
                </select>
            </div>
        </div>
        <div class="annytab-basic-space"></div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(linkname_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtStandardLinkname" type="text" class="annytab-form-textbox" tabindex="-1" readonly="readonly" value="@standardWeblink.link_name" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">&nbsp;</div>
            <div class="annytab-input-form-column-input"><input name="txtTranslatedLinkname" type="text" class="annytab-form-textbox" value="@(translatedWeblink != null ? translatedWeblink.link_name : "")" @(languageId == 0 ? Html.Raw("readonly='readonly'") : Html.Raw("")) /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(url_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtStandardUrl" type="text" class="annytab-form-textbox" tabindex="-1" readonly="readonly" value="@standardWeblink.url" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">&nbsp;</div>
            <div class="annytab-input-form-column-input"><input name="txtTranslatedUrl" type="text" class="annytab-form-textbox" @(languageId == 0 ? Html.Raw("readonly='readonly'") : Html.Raw("")) value="@(translatedWeblink != null ? translatedWeblink.url : "")" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(inactive_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="cbInactive" type="checkbox" class="annytab-form-checkbox" value="true" @(translatedWeblink != null && translatedWeblink.inactive == true ? Html.Raw("checked='checked'") : Html.Raw("")) @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) /></div>
        </div>
    </div>

    @*Button panel*@
    <div style="display:block;border:1px solid #cccccc;margin:20px 0px 0px 0px;border-radius:4px;">
        <input id="btnSave" type="submit" class="annytab-form-button" value="@translate_tt" @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) />
        <input data-id="deletePost" type="button" class="annytab-form-button" value="@delete_tt" @(Html.Raw("data-url='/admin_weblinks/delete/" + standardWeblink.id.ToString() + "?returnUrl=" + Server.UrlEncode(returnUrl) + "&lang=" + languageId.ToString() + "'")) @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) />
        <input type="button" class="annytab-form-button" value="@cancel_tt" onclick="@Html.Raw("location.href='" + returnUrl + "'")" />
    </div>
}

@section scripts {
    <script type="text/javascript">
        $("#selectLanguage").focus();
        $("#selectLanguage").on("change", function () { $(location).attr("href", $(this).find(":selected").attr("data-url")); });
    </script>
}