Blogsite/Controllers/admin_media_filesController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace Annytab.Blogsite.Controllers
{
    /// <summary>
    /// This class controls the administration of media files
    /// </summary>
    [ValidateInput(false)]
    public class admin_media_filesController : Controller
    {
        #region View methods

        // Get the list of media files
        // GET: /admin_media_files/
        [HttpGet]
        public ActionResult index()
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query paramaters
            ViewBag.QueryParams = new QueryParams(Request);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                ViewBag.AdminSession = true;
                return View();
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

        } // End of the index method

        // Search in the list
        // POST: /admin_media_files/search
        [HttpPost]
        public ActionResult search(FormCollection collection)
        {
            // Get the keywords
            string keywordString = collection["txtSearch"];
            string sort_field = collection["selectSortField"];
            string sort_order = collection["selectSortOrder"];
            string page_size = collection["selectPageSize"];

            // Return the url with search parameters
            return Redirect("/admin_media_files?kw=" + Server.UrlEncode(keywordString) + "&sf=" + sort_field + "&so=" + sort_order + "&pz=" + page_size);

        } // End of the search method

        // Get the edit form
        // GET: /admin_media_files/edit/1?returnUrl=?kw=df&so=ASC
        [HttpGet]
        public ActionResult edit(Int32 id = 0, string returnUrl = "/admin_media_files")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor", "Author" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default admin language
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Add data to the view
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.Languages = Language.GetAll(currentDomain.back_end_language, "name", "ASC");
            ViewBag.MediaFile = MediaFile.GetOneById(id);
            ViewBag.ReturnUrl = returnUrl;

            // Create a new empty media file post if the media file does not exist
            if (ViewBag.MediaFile == null)
            {
                // Add data to the view
                ViewBag.MediaFile = new MediaFile();
            }

            // Return the edit view
            return View("edit");

        } // End of the edit method

        #endregion

        #region Post methods

        // Update the media file
        // POST: /admin_media_files/edit
        [HttpPost]
        public ActionResult edit(FormCollection collection)
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get the return url
            string returnUrl = collection["returnUrl"];
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor", "Author" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get all the form values
            Int32 id = Convert.ToInt32(collection["txtId"]);
            string title = collection["txtTitle"];
            string media_type = collection["selectMediaType"];
            HttpPostedFileBase media_file_content = Request.Files["uploadMediaFile"];

            // Get the default admin language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get translated texts
            KeyStringList tt = StaticText.GetAll(adminLanguageId, "id", "ASC");

            // Get the media file post
            MediaFile mediaFilePost = MediaFile.GetOneById(id);
            bool postExists = true;

            // Check if the media files exists
            if (mediaFilePost == null)
            {
                // Create an empty media file
                mediaFilePost = new MediaFile();
                postExists = false;
            }

            // Update values
            mediaFilePost.title = title;
            mediaFilePost.media_type = media_type;

            // Create a error message
            string errorMessage = string.Empty;

            // Check for errors in the campaign
            if (mediaFilePost.title.Length > 100)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_length"), tt.Get("title"), "100") + "<br/>";
            }

            // Check if there is errors
            if (errorMessage == string.Empty)
            {
                // Check if we should add the media file
                if (postExists == false)
                {
                    // Add the media file
                    Int64 insertId = MediaFile.Add(mediaFilePost);
                    mediaFilePost.id = Convert.ToInt32(insertId);
                }

                // Update the media file
                if (media_file_content.ContentLength > 0)
                {
                    UpdateMediaFile(mediaFilePost, media_file_content);
                }

                // Update the media file
                MediaFile.Update(mediaFilePost);

                // Redirect the user to the list
                return Redirect(returnUrl);
            }
            else
            {
                // Set form values
                ViewBag.ErrorMessage = errorMessage;
                ViewBag.TranslatedTexts = tt;
                ViewBag.MediaFile = mediaFilePost;
                ViewBag.ReturnUrl = returnUrl;

                // Return the edit view
                return View("edit");
            }

        } // End of the edit method

        // Delete the media file
        // POST: /admin_media_files/delete/1?returnUrl=?kw=sok&qp=2
        [HttpGet]
        public ActionResult delete(Int32 id = 0, string returnUrl = "/admin_media_files")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor", "Author" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the media file post
            MediaFile mediaFilePost = MediaFile.GetOneById(id);

            // Create an error code variable
            Int32 errorCode = 0;

            // Delete the media file post and all the connected posts (CASCADE)
            errorCode = MediaFile.DeleteOnId(id);

            // Check if there is an error
            if (errorCode != 0)
            {
                ViewBag.AdminErrorCode = errorCode;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }

            // Delete the media file
            if (mediaFilePost != null)
            {
                DeleteMediaFile(mediaFilePost.src);
            }

            // Redirect the user to the list
            return Redirect(returnUrl);

        } // End of the delete method

        #endregion

        #region Helper methods

Blogsite/Views/admin_media_files/_form_menu.cshtml
@{
    // Get the form data
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_media_files" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;
    
    // Get translated texts
    string show_tt = tt.Get("show");
    string list_tt = tt.Get("list");
    string new_tt = tt.Get("new");
    string search_tt = tt.Get("search");
    string id_tt = tt.Get("id");
    string title_tt = tt.Get("title");
    string media_type_tt = tt.Get("media_type");
    string source_tt = tt.Get("source");
    string ascending_tt = tt.Get("ascending");
    string descending_tt = tt.Get("descending");
    string sort_tt = tt.Get("sort");
    string on_tt = tt.Get("on");
}

@*The menu bar*@
<div class="annytab-form-menubar">
    @using (Html.BeginForm("search", "admin_media_files", FormMethod.Post))
    {
        <input type="button" class="annytab-form-button" value="@(show_tt + " " + list_tt.ToLower())" onclick="location.href='@Url.Action("index", "admin_media_files", new { sf = parameters.sort_field, so = parameters.sort_order, pz = parameters.page_size })'" />
        <input type="button" class="annytab-form-button" value="@new_tt" onclick="location.href='@Url.Action("edit", "admin_media_files", new { id = 0, returnUrl = queryString })'" />
        <select name="selectSortField" class="annytab-form-select" style="width:100px;">
            <option value="id" @(parameters.sort_field == "" ? Html.Raw("selected='selected'") : Html.Raw(""))>@(sort_tt + " " + on_tt.ToLower())</option>
            <option value="id" @(parameters.sort_field == "id" ? Html.Raw("selected='selected'") : Html.Raw(""))>@id_tt</option>
            <option value="title" @(parameters.sort_field == "title" ? Html.Raw("selected='selected'") : Html.Raw(""))>@title_tt</option>
            <option value="media_type" @(parameters.sort_field == "media_type" ? Html.Raw("selected='selected'") : Html.Raw(""))>@media_type_tt</option>
            <option value="src" @(parameters.sort_field == "src" ? Html.Raw("selected='selected'") : Html.Raw(""))>@source_tt</option>
        </select>
        <select name="selectSortOrder" class="annytab-form-select" style="width:80px;">
            <option value="ASC" @(parameters.sort_order == "ASC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@ascending_tt</option>
            <option value="DESC" @(parameters.sort_order == "DESC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@descending_tt</option>
        </select>
        <select name="selectPageSize" class="annytab-form-select" style="width:50px;">
            <option value="10" @(parameters.page_size == 10 ? Html.Raw("selected='selected'") : Html.Raw(""))>10</option>
            <option value="20" @(parameters.page_size == 20 ? Html.Raw("selected='selected'") : Html.Raw(""))>20</option>
            <option value="40" @(parameters.page_size == 40 ? Html.Raw("selected='selected'") : Html.Raw(""))>40</option>
            <option value="80" @(parameters.page_size == 80 ? Html.Raw("selected='selected'") : Html.Raw(""))>80</option>
        </select>
        <input id="txtSearch" name="txtSearch" type="text" class="annytab-form-textbox" style="width:150px;" value="@Server.UrlDecode(parameters.keywords)" />
        <input type="submit" class="annytab-form-button" value="@search_tt" />
    }
</div>

Blogsite/Views/admin_media_files/edit.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get form data
    MediaFile mediaFile = ViewBag.MediaFile;
    KeyStringList tt = ViewBag.TranslatedTexts;
    string returnUrl = ViewBag.ReturnUrl;
    string error_message = ViewBag.ErrorMessage != null ? ViewBag.ErrorMessage : string.Empty;

    // Get translated texts
    string media_file_tt = tt.Get("media_file");
    string new_tt = tt.Get("new");
    string edit_tt = tt.Get("edit");
    string id_tt = tt.Get("id");
    string title_tt = tt.Get("title");
    string media_type_tt = tt.Get("media_type");
    string source_tt = tt.Get("source");
    string preview_tt = tt.Get("preview");
    string save_tt = tt.Get("save");
    string cancel_tt = tt.Get("cancel");

    // Set the title for the page
    if (mediaFile.id == 0)
    {
        ViewBag.Title = media_file_tt + " - " + new_tt.ToLower();
    }
    else
    {
        ViewBag.Title = media_file_tt + " - " + edit_tt.ToLower();
    }
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("/Views/admin_media_files/_form_menu.cshtml")

@*Main form*@
@using (Html.BeginForm("edit", "admin_media_files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*Hidden data*@
    <input name="returnUrl" type="hidden" value="@returnUrl" />
    <div class="annytab-form-error-message" style="@(error_message != "" ? "display:block;" : "display:none;")">@Html.Raw(error_message)</div>
    
    @*Input form table*@
    <div class="annytab-input-form-table">
        <div class="annytab-input-form-row" style="@(mediaFile.id != 0 ? "display:table-row;" : "display:none;")">
            <div class="annytab-input-form-column-label">@(id_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtId" type="text" class="annytab-form-textbox" tabindex="-1" readonly="readonly" value="@mediaFile.id" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(title_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input id="txtTitle" name="txtTitle" type="text" class="annytab-form-textbox" value="@mediaFile.title" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(media_type_tt + ":")</div>
            <div class="annytab-input-form-column-input">
                <select id="selectMediaType" name="selectMediaType" class="annytab-form-select">
                    <option value="image" @(mediaFile.media_type == "image" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Image")</option>
                    <option value="url" @(mediaFile.media_type == "url" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Url")</option>
                    <option value="object" @(mediaFile.media_type == "object" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Object")</option>
                    <option value="iframe" @(mediaFile.media_type == "iframe" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Iframe")</option>
                    <option value="video_mp4" @(mediaFile.media_type == "video_mp4" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Video/MP4")</option>
                    <option value="video_webm" @(mediaFile.media_type == "video_webm" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Video/WebM")</option>
                    <option value="video_ogg" @(mediaFile.media_type == "video_ogg" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Video/Ogg")</option>
                    <option value="audio_mpeg" @(mediaFile.media_type == "audio_mpeg" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Audio/MP3")</option>
                    <option value="audio_wav" @(mediaFile.media_type == "audio_wav" ? Html.Raw("selected='selected'") : Html.Raw(""))>@("Audio/Wav")</option>
                </select>
            </div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(source_tt + ":")</div>
            <div class="annytab-input-form-column-input"><div id="mediaFileSource" class="annytab-form-label">@(mediaFile.src == "" ? " --- " : mediaFile.src)</div></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(media_file_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input id="uploadMediaFile" name="uploadMediaFile" type="file" class="annytab-form-upload" /></div>
        </div>
    </div>
    
    @*Button panel*@
    <div style="display:block;border:1px solid #cccccc;margin: 20px 0px 0px 0px;border-radius: 4px;">
        <input id="btnPreviewMediaFile" type="button" class="annytab-form-button" value="@preview_tt" />
        <input id="btnSave" type="submit" class="annytab-form-button" value="@save_tt" />
        <input type="button" class="annytab-form-button" value="@cancel_tt" onclick="@Html.Raw("location.href='" + returnUrl + "'")" />
    </div>
}

@section scripts {
    <script type="text/javascript">
        $("#txtTitle").focus(); 
        $("#btnPreviewMediaFile").click(previewMediaFile);

        // Preview the media file
        function previewMediaFile()
        {
            // Get values
            var file = null;
            var reader = new FileReader();

            if (document.getElementById("uploadMediaFile").files.length > 0)
            {
                var file = document.getElementById("uploadMediaFile").files[0];
            }

            try
            {
                // Load the media file
                reader.onload = function ()
                {
                    printHtmlDocument(reader.result);
                }
            
                // Check if we should change the source
                if (file != null)
                {
                    // Read the source from the file
                    reader.readAsDataURL(file);
                }
                else
                {
                    printHtmlDocument($("#mediaFileSource").html());
                }
            }
            catch(err)
            {
                alert(err);
            }

        } // End of the previewMediaFile method

        // Print the html document
        function printHtmlDocument(src)
        {
            // Get values
            var title = $("#txtTitle").val();
            var mediaType = $("#selectMediaType").val();

            // Create the string to return
            var html = "<html><head><title>" + title + "</title></head><body>";

            // Set the media content
            html += getMediaFileContent(title, mediaType, src);
            
            // Add the final touch to the html
            html += "</body></html>";

            // Calculate offsets
            var left = (screen.width / 2) - (1280 / 2);
            var top = (screen.height / 2) - (720 / 2);

            // Create the preview window
            var printWindow = window.open("", "", "resizable=yes,scrollbars=yes,height=720,width=1280,top=" + top + ",left=" + left, true);
            printWindow.document.write(html);
            printWindow.document.close();

        } // End of the printHtmlDocument method
    
    </script>
}

Blogsite/Views/admin_media_files/index.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get the form data
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_media_files" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;

    // Create a clean string with keywords
    string cleanKeywords = parameters.keywords.Replace("+", "");

    // Create an array with search words
    string[] words = cleanKeywords.Split(' ');

    // Count the number of posts
    Int32 count = MediaFile.GetCountBySearch(words);

    // Get the number of pages
    Int32 numberOfPages = Convert.ToInt32(Math.Ceiling(((double)count / parameters.page_size)));
    numberOfPages = numberOfPages == 0 ? 1 : numberOfPages;

    // Get media files by keywords in a search
    List<MediaFile> mediaFiles = MediaFile.GetBySearch(words, parameters.page_size, parameters.current_page, parameters.sort_field, parameters.sort_order);

    // Get translated texts
    string media_file_tt = tt.Get("media_file");
    string list_tt = tt.Get("list");
    string id_tt = tt.Get("id");
    string title_tt = tt.Get("title");
    string media_type_tt = tt.Get("media_type");
    string source_tt = tt.Get("source");
    string edit_tt = tt.Get("edit");
    string delete_tt = tt.Get("delete");

    // Set paging data
    ViewBag.CurrentPage = parameters.current_page;
    ViewBag.NumberOfPages = numberOfPages;
    ViewBag.NavigateUrl = "/admin_media_files?kw=" + Server.UrlEncode(parameters.keywords) + "&sf=" + parameters.sort_field + "&so=" + parameters.sort_order + "&pz=" + parameters.page_size + "&qp={0}";

    // Set the page title
    ViewBag.Title = media_file_tt + " - " + list_tt.ToLower();
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_media_files/_form_menu.cshtml")

@*List of media files*@
<div class="annytab-list-container">
    <div class="annytab-list-table" style="width:948px;">
        <div class="anntyab-list-row">
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@id_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@title_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@media_type_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@source_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@edit_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@delete_tt</div>
        </div>

        @for (int i = 0; i < mediaFiles.Count; i++)
        {
            @:<div class="@(i % 2 != 0 ? "annytab-list-row-main" : "annytab-list-row-alt")">
            @:<div class="annytab-list-column" style="text-align:center;width:100px;">@mediaFiles[i].id.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@mediaFiles[i].title</div>
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@mediaFiles[i].media_type</div>
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@mediaFiles[i].src</div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@edit_tt" onclick="location.href='@Url.Action("edit", "admin_media_files", new { id = mediaFiles[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input data-id="deletePost" type="button" class="annytab-form-button" value="@delete_tt" @(Html.Raw("data-url='/admin_media_files/delete/" + mediaFiles[i].id + "?returnUrl=" + Server.UrlEncode(queryString) + "'")) /></div>
            @:</div>
        }
    </div>
</div>

@*Paging menu*@
@Html.Partial("/Views/shared_admin/_paging_menu.cshtml")

@section scripts {
    <script type="text/javascript">$("#txtSearch").focus();</script>
}