Blogsite/Controllers/admin_categoriesController.cs
using System;
using System.Web.Mvc;

namespace Annytab.Blogsite.Controllers
{
    /// <summary>
    /// This class controls the administration of categories
    /// </summary>
    [ValidateInput(false)]
    public class admin_categoriesController : Controller
    {
        #region View methods

        // Get the list of categories
        // GET: /admin_categories/
        [HttpGet]
        public ActionResult index()
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query paramaters
            ViewBag.QueryParams = new QueryParams(Request);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                ViewBag.AdminSession = true;
                return View();
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

        } // End of the index method

        // Search in the list
        // POST: /admin_categories/search
        [HttpPost]
        public ActionResult search(FormCollection collection)
        {
            // Get the search data
            string keywordString = collection["txtSearch"];
            string sort_field = collection["selectSortField"];
            string sort_order = collection["selectSortOrder"];
            string page_size = collection["selectPageSize"];

            // Return the url with search parameters
            return Redirect("/admin_categories?kw=" + Server.UrlEncode(keywordString) + "&sf=" + sort_field + "&so=" + sort_order + "&pz=" + page_size);

        } // End of the search method

        // Get the edit form
        // GET: /admin_categories/edit/1?returnUrl=?kw=df&so=ASC
        [HttpGet]
        public ActionResult edit(Int32 id = 0, string returnUrl = "/admin_categories")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query paramaters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the administrator default language
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Add data to the view
            ViewBag.Category = Category.GetOneById(id, adminLanguageId);
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.ReturnUrl = returnUrl;

            // Check if the category is null
            if (ViewBag.Category == null)
            {
                // Create a new empty category
                ViewBag.Category = new Category();
            }

            // Return the edit view
            return View("edit");

        } // End of the edit method

        // Get the translate form
        // GET: /admin_categories/translate/1?returnUrl=?kw=df&so=ASC
        [HttpGet]
        public ActionResult translate(Int32 id = 0, string returnUrl = "/admin_categories")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query paramaters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor", "Translator" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get the language id
            int languageId = 0;
            if (Request.Params["lang"] != null)
            {
                Int32.TryParse(Request.Params["lang"], out languageId);
            }

            // Add data to the form
            ViewBag.LanguageId = languageId;
            ViewBag.Languages = Language.GetAll(adminLanguageId, "name", "ASC");
            ViewBag.StandardCategory = Category.GetOneById(id, adminLanguageId);
            ViewBag.TranslatedCategory = Category.GetOneById(id, languageId);
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.ReturnUrl = returnUrl;

            // Return the view
            if (ViewBag.StandardCategory != null)
            {
                return View("translate");
            }
            else
            {
                return Redirect(returnUrl);
            }

        } // End of the translate method

        #endregion

        #region Post methods

        // Update the category
        // POST: /admin_categories/edit
        [HttpPost]
        public ActionResult edit(FormCollection collection)
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get the return url
            string returnUrl = collection["returnUrl"];
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get form values
            Int32 id = Convert.ToInt32(collection["txtId"]);
            Int32 parentCategoryId = Convert.ToInt32(collection["selectCategory"]);
            string title = collection["txtTitle"];
            string description = collection["txtDescription"];
            string metaDescription = collection["txtMetaDescription"];
            string metaKeywords = collection["txtMetaKeywords"];
            string pageName = collection["txtPageName"];
            string metaRobots = collection["selectMetaRobots"];
            DateTime date_added = DateTime.MinValue;
            DateTime.TryParse(collection["txtDateAdded"], out date_added);
            bool inactive = Convert.ToBoolean(collection["cbInactive"]);

            // Get the default admin language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get the category
            Category category = Category.GetOneById(id, adminLanguageId);

            // Get translated texts
            KeyStringList tt = StaticText.GetAll(adminLanguageId, "id", "ASC");

            // Check if the category exists
            if (category == null)
            {
                // Create a new category
                category = new Category();
            }

            // Set values for the category
            category.parent_category_id = parentCategoryId;
            category.title = title;
            category.main_content = description;
            category.meta_description = metaDescription;
            category.meta_keywords = metaKeywords;
            category.page_name = pageName;
            category.meta_robots = metaRobots;
            category.date_added = AnnytabDataValidation.TruncateDateTime(date_added);
            category.inactive = inactive;

            // Create a error message
            string errorMessage = string.Empty;

            // Get a category on page name
            Category categoryOnPageName = Category.GetOneByPageName(category.page_name, adminLanguageId);

            // Check the page name
            if (categoryOnPageName != null && category.id != categoryOnPageName.id)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_language_unique"), tt.Get("page_name")) + "<br/>";
            }
            if (category.page_name == string.Empty)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_required"), tt.Get("page_name")) + "<br/>";
            }
            if (AnnytabDataValidation.CheckPageNameCharacters(category.page_name) == false)
            {

Blogsite/Views/admin_categories/_form_menu.cshtml
@{
    // Get the form data
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_categories" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;
    
    // Get translated texts
    string show_tt = tt.Get("show");
    string list_tt = tt.Get("list");
    string new_tt = tt.Get("new");
    string search_tt = tt.Get("search");
    string id_tt = tt.Get("id");
    string title_tt = tt.Get("title");
    string page_views_tt = tt.Get("page_views");
    string date_tt = tt.Get("date");
    string inactive_tt = tt.Get("inactive");
    string ascending_tt = tt.Get("ascending");
    string descending_tt = tt.Get("descending");
    string sort_tt = tt.Get("sort");
    string on_tt = tt.Get("on");
}

@*The menu bar*@
<div class="annytab-form-menubar">
    @using (Html.BeginForm("search", "admin_categories", FormMethod.Post))
    {
        <input type="button" class="annytab-form-button" value="@(show_tt + " " + list_tt.ToLower())" onclick="location.href='@Url.Action("index", "admin_categories", new { sf = parameters.sort_field, so = parameters.sort_order, pz = parameters.page_size } )'" />
        <input type="button" class="annytab-form-button" value="@new_tt" onclick="location.href='@Url.Action("edit", "admin_categories", new { id = 0, returnUrl = queryString })'" />
        <select name="selectSortField" class="annytab-form-select "style="width:100px;">
            <option value="id" @(parameters.sort_field == "" ? Html.Raw("selected='selected'") : Html.Raw(""))>@(sort_tt + " " + on_tt.ToLower())</option>
            <option value="id" @(parameters.sort_field == "id" ? Html.Raw("selected='selected'") : Html.Raw(""))>@id_tt</option>
            <option value="title" @(parameters.sort_field == "title" ? Html.Raw("selected='selected'") : Html.Raw(""))>@title_tt</option>
            <option value="page_views" @(parameters.sort_field == "page_views" ? Html.Raw("selected='selected'") : Html.Raw(""))>@page_views_tt</option>
            <option value="date_added" @(parameters.sort_field == "date_added" ? Html.Raw("selected='selected'") : Html.Raw(""))>@date_tt</option>
            <option value="inactive" @(parameters.sort_field == "inactive" ? Html.Raw("selected='selected'") : Html.Raw(""))>@inactive_tt</option>
        </select>
        <select name="selectSortOrder" class="annytab-form-select" style="width:80px;">
            <option value="ASC" @(parameters.sort_order == "ASC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@ascending_tt</option>
            <option value="DESC" @(parameters.sort_order == "DESC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@descending_tt</option>
        </select>
        <select name="selectPageSize" class="annytab-form-select" style="width:50px;">
            <option value="10" @(parameters.page_size == 10 ? Html.Raw("selected='selected'") : Html.Raw(""))>10</option>
            <option value="20" @(parameters.page_size == 20 ? Html.Raw("selected='selected'") : Html.Raw(""))>20</option>
            <option value="40" @(parameters.page_size == 40 ? Html.Raw("selected='selected'") : Html.Raw(""))>40</option>
            <option value="80" @(parameters.page_size == 80 ? Html.Raw("selected='selected'") : Html.Raw(""))>80</option>
        </select>
        <input id="txtSearch" name="txtSearch" type="text" class="annytab-form-textbox" style="width:150px" value="@Server.UrlDecode(parameters.keywords)" />
        <input type="submit" class="annytab-form-button" value="@search_tt" />
    }
</div>

Blogsite/Views/admin_categories/edit.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get the current domain
    Domain domain = ViewBag.CurrentDomain;

    // Get values
    List<Category> mainCategories = Category.GetChildCategories(0, domain.back_end_language, "title", "ASC");
    Category category = ViewBag.Category;
    string returnUrl = ViewBag.ReturnUrl;
    string error_message = ViewBag.ErrorMessage != null ? ViewBag.ErrorMessage : string.Empty;
    KeyStringList tt = ViewBag.TranslatedTexts;

    // Get translated texts
    string category_tt = tt.Get("category");
    string new_tt = tt.Get("new");
    string edit_tt = tt.Get("edit");
    string main_category_tt = tt.Get("main_category");
    string no_choice_tt = tt.Get("no_choice");
    string id_tt = tt.Get("id");
    string title_tt = tt.Get("title");
    string description_tt = tt.Get("description");
    string meta_description_tt = tt.Get("meta_description");
    string keywords_tt = tt.Get("keywords");
    string page_name_tt = tt.Get("page_name");
    string date_tt = tt.Get("date");
    string added_tt = tt.Get("added");
    string inactive_tt = tt.Get("inactive");
    string save_tt = tt.Get("save");
    string cancel_tt = tt.Get("cancel");

    // Set the title for the page
    if (category.id == 0)
    {
        ViewBag.Title = category_tt + " - " + new_tt.ToLower();
    }
    else
    {
        ViewBag.Title = category_tt + " - " + edit_tt.ToLower();
    }
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("/Views/admin_categories/_form_menu.cshtml")

@*Main form*@
@using (Html.BeginForm("edit", "admin_categories", FormMethod.Post))
{
    @*Hidden data*@
    <input name="returnUrl" type="hidden" value="@returnUrl" />
    <div class="annytab-form-error-message" style="@(error_message != "" ? "display:block;" : "display:none;")">@Html.Raw(error_message)</div>
    
    @*Title and content*@
    <div class="annytab-form-input-container">
        <div class="annytab-form-title">@(title_tt)</div>
        <div><input id="txtTitle" name="txtTitle" type="text" class="annytab-form-textbox" style="max-width:100%;" value="@category.title" /></div>
        <div class="annytab-basic-space-half"></div>
        <div class="annytab-form-title">@(description_tt)</div>
        <div class="annytab-form-html-button-panel" data-textarea="txtDescription"></div>
        <div><textarea id="txtDescription" name="txtDescription" class="annytab-form-textarea" contenteditable="true" spellcheck="false" style="max-width:100%;" rows="10">@category.main_content</textarea></div>
    </div>
    
    <div class="annytab-basic-line"></div>
    
    @*Input form table*@
    <div class="annytab-input-form-table">
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(main_category_tt + ":")</div>
            <div class="annytab-input-form-column-input">
                <select id="selectCategory" name="selectCategory" class="annytab-form-select">
                    <option value="0" @(category.parent_category_id == 0 ? Html.Raw("selected='selected'") : Html.Raw(""))>@("-- " + no_choice_tt + " --")</option>
                    @CreateChildOptions(0, mainCategories, category.parent_category_id, domain.back_end_language)
                </select>
            </div>
        </div>
        <div class="annytab-input-form-row" style="@(category.id != 0 ? "display:table-row;" : "display:none;")">
            <div class="annytab-input-form-column-label">@(id_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtId" type="text" class="annytab-form-textbox" tabindex="-1" readonly="readonly" value="@category.id" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(meta_description_tt + ":")</div>
            <div class="annytab-input-form-column-input"><textarea name="txtMetaDescription" class="annytab-form-textarea" rows="3">@category.meta_description</textarea></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(keywords_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtMetaKeywords" type="text" class="annytab-form-textbox" value="@category.meta_keywords" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@("Robots:")</div>
            <div class="annytab-input-form-column-input">
                <select name="selectMetaRobots" class="annytab-form-select">
                    <option value="index, follow" @(category.meta_robots == "index, follow" ? Html.Raw("selected='selected'") : Html.Raw(""))>index, follow</option>
                    <option value="index, nofollow" @(category.meta_robots == "index, nofollow" ? Html.Raw("selected='selected'") : Html.Raw(""))>index, nofollow</option>
                    <option value="noindex, follow" @(category.meta_robots == "noindex, follow" ? Html.Raw("selected='selected'") : Html.Raw(""))>noindex, follow</option>
                    <option value="noindex, nofollow" @(category.meta_robots == "noindex, nofollow" ? Html.Raw("selected='selected'") : Html.Raw(""))>noindex, nofollow</option>
                </select>
            </div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(page_name_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="txtPageName" type="text" class="annytab-form-textbox" value="@category.page_name" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(added_tt + ", " + date_tt.ToLower() + " (yyyy-mm-dd):")</div>
            <div class="annytab-input-form-column-input"><input id="txtDateAdded" name="txtDateAdded" type="text" class="annytab-form-textbox" value="@category.date_added.ToString("yyyy-MM-dd")" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(inactive_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input name="cbInactive" type="checkbox" class="annytab-form-checkbox" value="true" @(category != null && category.inactive == true ? Html.Raw("checked='checked'") : Html.Raw("")) /></div>
        </div>
    </div>

    @*Button panel*@
    <div style="display:block;border: 1px solid #cccccc;margin: 20px 0px 0px 0px;border-radius: 4px;">
        <input id="btnSave" class="annytab-form-button" type="submit" value="@save_tt" />
        <input type="button" class="annytab-form-button" value="@cancel_tt" onclick="@Html.Raw("location.href='" + returnUrl + "'")" />
    </div>
}

@section scripts {
    <link href="/Content/jquery_css/jquery-ui.min.css" rel="stylesheet" />
    <script src="/Scripts/rangyinputs-jquery.js"></script>
    <script src="/Scripts/annytab_admin/annytab.html-button-panel.js"></script>
    <script type="text/javascript">
        $("#selectCategory").focus(); $("#txtDateAdded").datepicker({ dateFormat: 'yy-mm-dd' });
        $(".annytab-form-html-button-panel").htmlButtonPanel({ buttonClass: "annytab-form-button" });
    </script>
}

@helper CreateChildOptions(Int32 level, List<Category> categories, Int32 categoryId, Int32 languageId)
{
    // Create the intendation
    string intendation = "";

    for (int i = 0; i < level; i++)
    {
        intendation += "-&nbsp;";
    }

    // Loop all the categories
    for (int i = 0; i < categories.Count; i++)
    {
        // Reset the level
        if (categories[i].parent_category_id == 0)
        {
            level = 0;
        }
        
        // Create the option
        <option style="@(categories[i].parent_category_id == 0 ? Html.Raw("background-color:#cccccc;") : Html.Raw("background-color:#ffffff;"))" value="@categories[i].id.ToString()" @(categoryId == categories[i].id ? Html.Raw("selected='selected'") : Html.Raw(""))>@Html.Raw(intendation + categories[i].title)</option>

        // Get the child categories
        List<Category> childCategories = Category.GetChildCategories(categories[i].id, languageId, "title", "ASC");

        if (childCategories.Count > 0)
        {
            level += 1;
            @CreateChildOptions(level, childCategories, categoryId, languageId);
        }
    }
}

Blogsite/Views/admin_categories/index.cshtml
@using System.Globalization
@using Annytab.Stemmer
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get form data
    Domain domain = ViewBag.CurrentDomain;
    Language currentLanguage = Language.GetOneById(domain.back_end_language);
    CultureInfo cultureInfo = Tools.GetCultureInfo(currentLanguage);
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_categories" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;

    // Create a clean string with keywords
    string cleanKeywords = parameters.keywords.Replace("+", "");

    // Create an array with search words
    string[] words = cleanKeywords.Split(' ');
    Stemmer stemmer = Tools.GetStemmer(currentLanguage);
    string[] steamWords = stemmer.GetSteamWords(words);

    // Count the number of posts
    Int32 count = Category.GetCountBySearch(steamWords, domain.back_end_language);

    // Get the number of pages
    Int32 numberOfPages = Convert.ToInt32(Math.Ceiling(((double)count / parameters.page_size)));
    numberOfPages = numberOfPages == 0 ? 1 : numberOfPages;

    // Get categories by keywords in search
    List<Category> categories = Category.GetBySearch(steamWords, domain.back_end_language, parameters.page_size, parameters.current_page, parameters.sort_field, parameters.sort_order);

    // Get translated texts
    string category_tt = tt.Get("category");
    string list_tt = tt.Get("list");
    string id_tt = tt.Get("id");
    string title_tt = tt.Get("title");
    string parent_tt = tt.Get("parent");
    string page_views_tt = tt.Get("page_views");
    string edit_tt = tt.Get("edit");
    string translate_tt = tt.Get("translate");
    string delete_tt = tt.Get("delete");

    // Set paging data
    ViewBag.CurrentPage = parameters.current_page;
    ViewBag.NumberOfPages = numberOfPages;
    ViewBag.NavigateUrl = "/admin_categories?kw=" + Server.UrlEncode(parameters.keywords) + "&sf=" + parameters.sort_field + "&so=" + parameters.sort_order + "&pz=" + parameters.page_size + "&qp={0}";

    // Set the page title
    ViewBag.Title = category_tt + " - " + list_tt.ToLower();
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_categories/_form_menu.cshtml")

@*List of categories*@
<div class="annytab-list-container">
    <div class="annytab-list-table" style="width:856px;">
        <div class="annytab-list-row">
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@id_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@title_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:100px;">@page_views_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@parent_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@edit_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@translate_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@delete_tt</div>
        </div>

        @for (int i = 0; i < categories.Count; i++)
        {
            @:<div class="@(i % 2 != 0 ? "annytab-list-row-main" : "annytab-list-row-alt")">
            @:<div class="annytab-list-column" style="text-align:center;width:100px;">@categories[i].id.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@categories[i].title.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:left;width:100px;">@categories[i].page_views.ToString("##,0.##", cultureInfo)</div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;">@categories[i].parent_category_id.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@edit_tt" onclick="location.href='@Url.Action("edit", "admin_categories", new { id = categories[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@translate_tt" onclick="location.href='@Url.Action("translate", "admin_categories", new { id = categories[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input data-id="deletePost" type="button" class="annytab-form-button" value="@delete_tt" @(Html.Raw("data-url='/admin_categories/delete/" + categories[i].id + "?returnUrl=" + Server.UrlEncode(queryString) + "'")) /></div>
            @:</div>
        }
    </div>
</div>

@*Paging menu*@
@Html.Partial("/Views/shared_admin/_paging_menu.cshtml")

@section scripts {
    <script type="text/javascript">$("#txtSearch").focus();</script>
}