Blogsite/Controllers/admin_static_textsController.cs
using System;
using System.Web.Mvc;

namespace Annytab.Blogsite.Controllers
{
    /// <summary>
    /// This class controls the administration of static texts
    /// </summary>
    [ValidateInput(false)]
    public class admin_static_textsController : Controller
    {
        #region View methods

        // Get the list of static texts
        // GET: /admin_static_texts/
        [HttpGet]
        public ActionResult index()
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query paramaters
            ViewBag.QueryParams = new QueryParams(Request);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View();
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

        } // End of the index method

        // Search in the list
        // POST: /admin_static_texts/search
        [HttpPost]
        public ActionResult search(FormCollection collection)
        {
            // Get the search data
            string keywordString = collection["txtSearch"];
            string sort_field = collection["selectSortField"];
            string sort_order = collection["selectSortOrder"];
            string page_size = collection["selectPageSize"];

            // Return the url with search parameters
            return Redirect("~/admin_static_texts?kw=" + Server.UrlEncode(keywordString) + "&sf=" + sort_field + "&so=" + sort_order + "&pz=" + page_size);

        } // End of the search method

        // Get the edit form
        // GET: /admin_static_texts/edit/1?returnUrl=?kw=sok&qp=2
        [HttpGet]
        public ActionResult edit(string id = "", string returnUrl = "/admin_static_texts")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default admin language
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Add data to the view
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.StaticText = StaticText.GetOneById(id, adminLanguageId);
            ViewBag.ReturnUrl = returnUrl;

            // Create new empty static text if the static text does not exist
            if (ViewBag.StaticText == null)
            {
                // Add data to the view
                ViewBag.StaticText = new StaticText();
            }

            // Return the edit view
            return View("edit");

        } // End of the edit method

        // Get the translate form
        // GET: /admin_static_texts/translate/1?returnUrl=?kw=sok&qp=2
        [HttpGet]
        public ActionResult translate(string id = "", string returnUrl = "/admin_static_texts")
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor", "Translator" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default admin language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get the language id
            int languageId = 0;
            if (Request.Params["lang"] != null)
            {
                Int32.TryParse(Request.Params["lang"], out languageId);
            }

            // Add data to the form
            ViewBag.LanguageId = languageId;
            ViewBag.Languages = Language.GetAll(adminLanguageId, "name", "ASC");
            ViewBag.StandardStaticText = StaticText.GetOneById(id, adminLanguageId);
            ViewBag.TranslatedStaticText = StaticText.GetOneById(id, languageId);
            ViewBag.TranslatedTexts = StaticText.GetAll(adminLanguageId, "id", "ASC");
            ViewBag.ReturnUrl = returnUrl;

            // Return the view
            if (ViewBag.StandardStaticText != null)
            {
                return View("translate");
            }
            else
            {
                return Redirect(returnUrl);
            }

        } // End of the translate method

        #endregion

        #region Post methods

        // Update the static text
        // POST: /admin_static_texts/edit
        [HttpPost]
        public ActionResult edit(FormCollection collection)
        {
            // Get the current domain
            Domain currentDomain = Tools.GetCurrentDomain();
            ViewBag.CurrentDomain = currentDomain;

            // Get query parameters
            string returnUrl = collection["returnUrl"];
            ViewBag.QueryParams = new QueryParams(returnUrl);

            // Check if the administrator is authorized
            if (Administrator.IsAuthorized(new string[] { "Administrator", "Editor" }) == true)
            {
                ViewBag.AdminSession = true;
            }
            else if (Administrator.IsAuthorized(Administrator.GetAllAdminRoles()) == true)
            {
                ViewBag.AdminSession = true;
                ViewBag.AdminErrorCode = 1;
                ViewBag.TranslatedTexts = StaticText.GetAll(currentDomain.back_end_language, "id", "ASC");
                return View("index");
            }
            else
            {
                // Redirect the user to the start page
                return RedirectToAction("index", "admin_login");
            }

            // Get the default admin language id
            Int32 adminLanguageId = currentDomain.back_end_language;

            // Get translated texts
            KeyStringList tt = StaticText.GetAll(adminLanguageId, "id", "ASC");

            // Get all the form values
            string staticTextId = collection["txtId"];
            string staticTextText = collection["txtText"];

            // Get the static text
            StaticText staticText = StaticText.GetOneById(staticTextId, adminLanguageId);
            bool postExists = true;

            // Check if the static text exists
            if (staticText == null)
            {
                // Create an empty static text
                staticText = new StaticText();
                staticText.id = staticTextId;
                postExists = false;
            }

            // Update values
            staticText.value = staticTextText;

            // Create a error message
            string errorMessage = string.Empty;

            // Check for errors in the static text
            if (AnnytabDataValidation.CheckPageNameCharacters(staticText.id) == false)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_bad_chars"), tt.Get("id")) + "<br/>";
            }
            if (staticText.id.Length == 0 || staticText.id.Length > 100)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_certain_length"), tt.Get("id"), "1", "100") + "<br/>";
            }
            if (staticText.value.Length > 200)
            {
                errorMessage += "&#149; " + String.Format(tt.Get("error_field_length"), tt.Get("text"), "200") + "<br/>";
            }

            // Check if there is errors
            if (errorMessage == string.Empty)
            {
                // Check if we should add or update the static text
                if (postExists == false)
                {
                    // Add the static text
                    StaticText.Add(staticText, adminLanguageId);
                }
                else
                {
                    // Update the static text
                    StaticText.Update(staticText, adminLanguageId);
                }

                // Redirect the user to the list
                return Redirect(returnUrl);
            }
            else
            {
                // Set form values
                ViewBag.ErrorMessage = errorMessage;
                ViewBag.StaticText = staticText;

Blogsite/Views/admin_static_texts/_form_menu.cshtml
@{
    // Get the form data
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_static_texts" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;
    
    // Get translated texts
    string show_tt = tt.Get("show");
    string list_tt = tt.Get("list");
    string new_tt = tt.Get("new");
    string search_tt = tt.Get("search");
    string id_tt = tt.Get("id");
    string text_tt = tt.Get("text");
    string ascending_tt = tt.Get("ascending");
    string descending_tt = tt.Get("descending");
    string sort_tt = tt.Get("sort");
    string on_tt = tt.Get("on");
}

@*The menu bar*@
<div class="annytab-form-menubar">
    @using (Html.BeginForm("search", "admin_static_texts", FormMethod.Post))
    {
        <input type="button" class="annytab-form-button" value="@(show_tt + " " + list_tt.ToLower())" onclick="location.href='@Url.Action("index", "admin_static_texts", new { sf = parameters.sort_field, so = parameters.sort_order, pz = parameters.page_size })'" />
        <input type="button" class="annytab-form-button" value="@new_tt" onclick="location.href='@Url.Action("edit", "admin_static_texts", new { id = "", returnUrl = queryString })'" />
        <select name="selectSortField" class="annytab-form-select" style="width:100px;">
            <option value="id" @(parameters.sort_field == "" ? Html.Raw("selected='selected'") : Html.Raw(""))>@(sort_tt + " " + on_tt.ToLower())</option>
            <option value="id" @(parameters.sort_field == "id" ? Html.Raw("selected='selected'") : Html.Raw(""))>@id_tt</option>
            <option value="value" @(parameters.sort_field == "value" ? Html.Raw("selected='selected'") : Html.Raw(""))>@text_tt</option>
        </select>
        <select name="selectSortOrder" class="annytab-form-select" style="width:80px;">
            <option value="ASC" @(parameters.sort_order == "ASC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@ascending_tt</option>
            <option value="DESC" @(parameters.sort_order == "DESC" ? Html.Raw("selected='selected'") : Html.Raw(""))>@descending_tt</option>
        </select>
        <select name="selectPageSize" class="annytab-form-select" style="width:50px;">
            <option value="10" @(parameters.page_size == 10 ? Html.Raw("selected='selected'") : Html.Raw(""))>10</option>
            <option value="20" @(parameters.page_size == 20 ? Html.Raw("selected='selected'") : Html.Raw(""))>20</option>
            <option value="40" @(parameters.page_size == 40 ? Html.Raw("selected='selected'") : Html.Raw(""))>40</option>
            <option value="80" @(parameters.page_size == 80 ? Html.Raw("selected='selected'") : Html.Raw(""))>80</option>
        </select>
        <input id="txtSearch" name="txtSearch" type="text" class="annytab-form-textbox" style="width:150px;" value="@Server.UrlDecode(parameters.keywords)" />
        <input type="submit" class="annytab-form-button" value="@search_tt" />
    }
</div>

Blogsite/Views/admin_static_texts/edit.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get form data
    StaticText staticText = ViewBag.StaticText;
    string returnUrl = ViewBag.ReturnUrl;
    KeyStringList tt = ViewBag.TranslatedTexts;
    string error_message = ViewBag.ErrorMessage != null ? ViewBag.ErrorMessage : string.Empty;

    // Get translated texts
    string static_text_tt = tt.Get("static_text");
    string new_tt = tt.Get("new");
    string edit_tt = tt.Get("edit");
    string id_tt = tt.Get("id");
    string text_tt = tt.Get("text");
    string save_tt = tt.Get("save");
    string cancel_tt = tt.Get("cancel");

    // Set the title for the page
    if (staticText.id == string.Empty)
    {
        ViewBag.Title = static_text_tt + " - " + new_tt.ToLower();
    }
    else
    {
        ViewBag.Title = static_text_tt + " - " + edit_tt.ToLower();
    }
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_static_texts/_form_menu.cshtml")

@*Main form*@
@using (Html.BeginForm("edit", "admin_static_texts", FormMethod.Post))
{
    @*Hidden data*@
    <input name="returnUrl" type="hidden" value="@returnUrl" />
    <div class="annytab-form-error-message" style="@(error_message != "" ? "display:block;" : "display:none;")">@Html.Raw(error_message)</div>

    @*Input form table*@
    <div class="annytab-input-form-table">
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(id_tt + ":")</div>
            <div class="annytab-input-form-column-input"><input id="txtId" name="txtId" type="text" class="annytab-form-textbox" value="@staticText.id" /></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(text_tt + ":")</div>
            <div class="annytab-input-form-column-input"><textarea id="txtText" name="txtText" class="annytab-form-textarea" rows="4">@staticText.value</textarea></div>
        </div>
    </div>

    @*Button panel*@
    <div style="display:block;border:1px solid #cccccc;margin:20px 0px 0px 0px;border-radius:4px;">
        <input id="btnSave" type="submit" class="annytab-form-button" value="@save_tt" />
        <input type="button" class="annytab-form-button" value="@cancel_tt" onclick="@Html.Raw("location.href='" + returnUrl + "'")" />
    </div> 
}

@section scripts {
    <script type="text/javascript">$("#txtId").val() == "" ? $("#txtId").focus() : $("#txtText").focus();</script>
}

Blogsite/Views/admin_static_texts/index.cshtml
@using Annytab.Stemmer
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get form data
    Domain domain = ViewBag.CurrentDomain;
    Language currentLanguage = Language.GetOneById(domain.back_end_language);
    QueryParams parameters = ViewBag.QueryParams;
    string queryString = "/admin_static_texts" + QueryParams.GetQueryString(parameters);
    KeyStringList tt = ViewBag.TranslatedTexts;

    // Create a clean string with keywords
    string cleanKeywords = parameters.keywords.Replace("+", "");

    // Create an array with search words
    string[] words = cleanKeywords.Split(' ');
    Stemmer stemmer = Tools.GetStemmer(currentLanguage);
    string[] steamWords = stemmer.GetSteamWords(words);

    // Count the number of posts
    Int32 count = StaticText.GetCountBySearch(steamWords, domain.back_end_language);

    // Get the number of pages
    Int32 numberOfPages = Convert.ToInt32(Math.Ceiling(((double)count / parameters.page_size)));
    numberOfPages = numberOfPages == 0 ? 1 : numberOfPages;

    // Get static texts by keywords in search
    List<StaticText> staticTexts = StaticText.GetBySearch(steamWords, domain.back_end_language, parameters.page_size, parameters.current_page,
        parameters.sort_field, parameters.sort_order);

    // Get translated texts
    string static_text_tt = tt.Get("static_text");
    string list_tt = tt.Get("list");
    string id_tt = tt.Get("id");
    string text_tt = tt.Get("text");
    string edit_tt = tt.Get("edit");
    string translate_tt = tt.Get("translate");
    string delete_tt = tt.Get("delete");

    // Set paging data
    ViewBag.CurrentPage = parameters.current_page;
    ViewBag.NumberOfPages = numberOfPages;
    ViewBag.NavigateUrl = "/admin_static_texts?kw=" + Server.UrlEncode(parameters.keywords) + "&sf=" + parameters.sort_field + "&so=" + parameters.sort_order + "&pz=" + parameters.page_size + "&qp={0}";

    // Set the page title
    ViewBag.Title = static_text_tt + " - " + list_tt.ToLower();
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_static_texts/_form_menu.cshtml")

@*List of static texts*@
<div class="annytab-list-container">
    <div class="annytab-list-table" style="width:840px;">
        <div class="annytab-list-row">
            <div class="annytab-list-column-head" style="text-align:left;width:200px;">@id_tt</div>
            <div class="annytab-list-column-head" style="text-align:left;width:300px;">@text_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@edit_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@translate_tt</div>
            <div class="annytab-list-column-head" style="text-align:center;width:100px;">@delete_tt</div>
        </div>

        @for (int i = 0; i < staticTexts.Count; i++)
        {
            @:<div class="@(i % 2 != 0 ? "annytab-list-row-main" : "annytab-list-row-alt")">
            @:<div class="annytab-list-column" style="text-align:left;width:200px;">@staticTexts[i].id.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:left;width:300px;">@staticTexts[i].value.ToString()</div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@edit_tt" onclick="location.href='@Url.Action("edit", "admin_static_texts", new { id = staticTexts[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input type="button" class="annytab-form-button" value="@translate_tt" onclick="location.href='@Url.Action("translate", "admin_static_texts", new { id = staticTexts[i].id, returnUrl = queryString })'" /></div>
            @:<div class="annytab-list-column" style="text-align:center;width:100px;"><input data-id="deletePost" type="button" class="annytab-form-button" value="@delete_tt" @(Html.Raw("data-url='/admin_static_texts/delete/" + staticTexts[i].id + "?returnUrl=" + Server.UrlEncode(queryString) + "'")) /></div>
            @:</div>
        }
    </div>
</div>

@*Paging menu*@
@Html.Partial("/Views/shared_admin/_paging_menu.cshtml")

@section scripts {
    <script type="text/javascript">$("#txtSearch").focus();</script>
}

Blogsite/Views/admin_static_texts/translate.cshtml
@{
    // Set the layout for the page
    Layout = "/Views/shared_admin/_standard_layout.cshtml";

    // Get values
    Int32 languageId = ViewBag.LanguageId;
    List<Language> languages = ViewBag.Languages;
    StaticText standardStaticText = ViewBag.StandardStaticText;
    StaticText translatedStaticText = ViewBag.TranslatedStaticText;
    KeyStringList tt = ViewBag.TranslatedTexts;
    string returnUrl = ViewBag.ReturnUrl;
    string error_message = ViewBag.ErrorMessage != null ? ViewBag.ErrorMessage : string.Empty;

    // Get translated texts
    string static_text_tt = tt.Get("static_text");
    string translate_tt = tt.Get("translate");
    string language_tt = tt.Get("language");
    string no_choice_tt = tt.Get("no_choice");
    string id_tt = tt.Get("id");
    string text_tt = tt.Get("text");
    string delete_tt = tt.Get("delete");
    string cancel_tt = tt.Get("cancel");

    // Set the title for the page
    ViewBag.Title = static_text_tt + " - " + translate_tt.ToLower();
}

@*Title*@
<h1>@ViewBag.Title</h1>

@*Menu*@
@Html.Partial("~/Views/admin_static_texts/_form_menu.cshtml")

@*Main form*@
@using (Html.BeginForm("translate", "admin_static_texts", FormMethod.Post))
{
    @*Hidden data*@
    <input name="returnUrl" type="hidden" value="@returnUrl" />
    <div class="annytab-form-error-message" style="@(error_message != "" ? "display:block;" : "display:none;")">@Html.Raw(error_message)</div>
    <input type="hidden" name="hiddenStaticTextId" value="@standardStaticText.id" />
    
    @*Input form table*@
    <div class="annytab-input-form-table">
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(language_tt + ":")</div>
            <div class="annytab-input-form-column-input">
                <select id="selectLanguage" name="selectLanguage" class="annytab-form-select">
                    <option value="0" data-url="@Url.Content("/admin_static_texts/translate/" + standardStaticText.id.ToString() + "?returnUrl=" + Server.UrlEncode(returnUrl))" @(languageId == 0 ? Html.Raw("selected='selected'") : Html.Raw(""))>@("-- " + no_choice_tt + " --")</option>
                    @foreach (Language language in languages)
                    {
                        <option value="@language.id" data-url="@Url.Content("/admin_static_texts/translate/" + standardStaticText.id.ToString() + "?returnUrl=" + Server.UrlEncode(returnUrl) + "&lang=" + language.id.ToString())" @(language.id == languageId ? Html.Raw("selected='selected'") : Html.Raw(""))>@language.name</option>
                    }
                </select>
            </div>
        </div>
        <div class="annytab-basic-space"></div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">@(text_tt + ":")</div>
            <div class="annytab-input-form-column-input"><textarea name="txtStandardText" class="annytab-form-textarea" tabindex="-1" readonly="readonly" rows="4">@standardStaticText.value</textarea></div>
        </div>
        <div class="annytab-input-form-row">
            <div class="annytab-input-form-column-label">&nbsp;</div>
            <div class="annytab-input-form-column-input"><textarea name="txtTranslatedText" class="annytab-form-textarea" @(languageId == 0 ? Html.Raw("readonly='readonly'") : Html.Raw("")) rows="4">@(translatedStaticText != null ? translatedStaticText.value : "")</textarea></div>
        </div>
    </div>

    @*Button panel*@
    <div style="display:block;border:1px solid #cccccc;margin:20px 0px 0px 0px;border-radius:4px;">
        <input id="btnSave" type="submit" class="annytab-form-button" value="@translate_tt" @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) />
        <input data-id="deletePost" type="button" class="annytab-form-button" value="@delete_tt" @(Html.Raw("data-url='/admin_static_texts/delete/" + standardStaticText.id.ToString() + "?returnUrl=" + Server.UrlEncode(returnUrl) + "&lang=" + languageId.ToString() + "'")) @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) @(languageId == 0 ? Html.Raw("disabled='disabled'") : Html.Raw("")) />
        <input type="button" class="annytab-form-button" value="@cancel_tt" onclick="@Html.Raw("location.href='" + returnUrl + "'")" />
    </div>
}

@section scripts {
    <script type="text/javascript">
        $("#selectLanguage").focus();
        $("#selectLanguage").on("change", function () { $(location).attr("href", $(this).find(":selected").attr("data-url")); });
    </script>
}